"""
Run the same pipeline as POST /analyze for fixed firms; write JSON + comparison notes.

Usage (from backend/, with .env and ANAKIN_API_KEY):
  .\\.venv\\Scripts\\python.exe scripts\\capture_analyze_outputs.py
  .\\.venv\\Scripts\\python.exe scripts\\capture_analyze_outputs.py --quick   # Stripe + Razorpay only

Outputs:
  artifacts/analyze_<slug>.json
  artifacts/ANALYZE_COMPARISON.md
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))


def _slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return s[:80] or "company"


def _trim_for_disk(obj: Any, max_holocron_chars: int = 12000) -> Any:
    """Keep files reviewable: truncate huge holocron `data` blobs."""
    if not isinstance(obj, dict):
        return obj
    out = dict(obj)
    hol = out.get("diagnostics", {}).get("holocron")
    if isinstance(hol, list):
        new_hol = []
        for row in hol:
            if not isinstance(row, dict):
                new_hol.append(row)
                continue
            r = dict(row)
            if "data" in r and r["data"] is not None:
                dumped = json.dumps(r["data"], default=str)
                if len(dumped) > max_holocron_chars:
                    r["data"] = {"_truncated": True, "_preview": dumped[:max_holocron_chars] + "..."}
            new_hol.append(r)
        diag = dict(out.get("diagnostics") or {})
        diag["holocron"] = new_hol
        out["diagnostics"] = diag
    return out


def _metrics(report: dict[str, Any]) -> dict[str, Any]:
    diag = report.get("diagnostics") or {}
    hol = diag.get("holocron") or []
    hol_ok = sum(1 for h in hol if isinstance(h, dict) and h.get("ok"))
    return {
        "company": report.get("company_name"),
        "score": report.get("score"),
        "confidence": report.get("confidence"),
        "evidence_count": len(report.get("evidence") or []),
        "risk_flags_count": len(report.get("risk_flags") or []),
        "catalysts_count": len(report.get("growth_catalysts") or []),
        "holocron_ok_count": hol_ok,
        "holocron_phase_error": diag.get("holocron_error"),
        "agentic_error": diag.get("agentic_search_error"),
        "map_error": diag.get("map_error"),
        "discovered_url_count": diag.get("discovered_url_count"),
    }


async def _run_one(company_name: str, website_url: str, ticker: str | None) -> dict[str, Any]:
    from app.main import analyze
    from app.models.schemas import AnalyzeRequest

    payload = AnalyzeRequest(
        company_name=company_name,
        website_url=website_url,  # type: ignore[arg-type]
        ticker=ticker,
    )
    resp = await analyze(payload)
    return resp.model_dump()


async def main() -> None:
    logging.basicConfig(level=logging.WARNING)

    quick = "--quick" in sys.argv
    firms: list[tuple[str, str, str | None]] = [
        ("Stripe", "https://stripe.com", None),
        ("Razorpay", "https://razorpay.com", None),
    ]
    if not quick:
        firms.append(("Apple Inc.", "https://www.apple.com", "AAPL"))

    ART.mkdir(parents=True, exist_ok=True)
    reports: list[tuple[str, dict[str, Any]]] = []

    for company_name, website_url, ticker in firms:
        slug = _slug(company_name)
        t0 = time.perf_counter()
        print("running", company_name, "...", flush=True)
        raw = await _run_one(company_name, website_url, ticker)
        elapsed = time.perf_counter() - t0
        raw["_capture_meta"] = {"elapsed_seconds": round(elapsed, 2), "website_url": website_url}
        disk = _trim_for_disk(raw)
        path = ART / f"analyze_{slug}.json"
        path.write_text(json.dumps(disk, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
        print("  wrote", path, f"elapsed_s={elapsed:.1f}", flush=True)
        reports.append((slug, raw))

    lines: list[str] = []
    lines.append("# Analyze capture — comparison\n")
    lines.append("Generated by `scripts/capture_analyze_outputs.py` (same logic as `POST /analyze`).\n")
    lines.append("JSON files may truncate `diagnostics.holocron[].data` for disk size; scores and evidence use full pipeline.\n")
    lines.append("\n## Side-by-side metrics\n")
    lines.append("| Company | Score | Confidence | Evidence | Risks | Holocron OK | Agentic err? | Map err? |\n")
    lines.append("|---------|------:|------------|---------:|------:|------------:|:-------------|:---------|\n")
    for slug, r in reports:
        m = _metrics(r)
        ae = "yes" if m["agentic_error"] else "no"
        me = "yes" if m["map_error"] else "no"
        lines.append(
            f"| {m['company']} | {m['score']} | {m['confidence']} | {m['evidence_count']} | "
            f"{m['risk_flags_count']} | {m['holocron_ok_count']} | {ae} | {me} |\n"
        )

    lines.append("\n## Holocron rows (summary)\n")
    for slug, r in reports:
        lines.append(f"### {r.get('company_name')}\n")
        hol = (r.get("diagnostics") or {}).get("holocron") or []
        if not hol:
            lines.append("_No holocron rows (disabled or empty)._\n")
            continue
        for row in hol:
            if not isinstance(row, dict):
                continue
            lines.append(
                f"- **{row.get('catalog_slug')}** — ok={row.get('ok')} action_id=`{row.get('action_id')}` "
                f"error={row.get('error')!r}\n"
            )

    lines.append("\n## Verdict — good to proceed?\n")
    ok = True
    reasons: list[str] = []
    for slug, r in reports:
        name = r.get("company_name")
        if r.get("score") is None:
            ok = False
            reasons.append(f"{name}: missing score")
        if not (r.get("evidence") or []):
            ok = False
            reasons.append(f"{name}: no evidence rows")
        diag = r.get("diagnostics") or {}
        if diag.get("holocron_error"):
            ok = False
            reasons.append(f"{name}: holocron phase error: {diag.get('holocron_error')}")
        hol = diag.get("holocron") or []
        if hol and not any(isinstance(h, dict) and h.get("ok") for h in hol):
            reasons.append(f"{name}: holocron ran but no catalog returned ok=True (check credits/schemas).")

    if ok and not reasons:
        lines.append(
            "**Yes — reasonable to proceed.** All three runs returned a score, evidence, and no holocron phase crash. "
            "Review JSON for narrative quality; agentic timeouts are acceptable if diagnostics explain them.\n"
        )
    else:
        lines.append("**Review before proceeding.**\n")
        for x in reasons:
            lines.append(f"- {x}\n")

    cmp_path = ART / "ANALYZE_COMPARISON.md"
    cmp_path.write_text("".join(lines), encoding="utf-8")
    print("wrote", cmp_path)


if __name__ == "__main__":
    asyncio.run(main())
